# Generated by Django 3.0.4 on 2020-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
