# Generated by Django 3.0.4 on 2020-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0004_auto_20200308_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='o.jpg', null=True, upload_to='books_images'),
        ),
    ]
