# Generated by Django 3.0.4 on 2020-03-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0005_auto_20200308_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin2.Book')),
            ],
        ),
    ]
