# Generated by Django 3.0.4 on 2020-03-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member'),
        ('admin2', '0006_book_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_order',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
    ]
