# Generated by Django 3.0.4 on 2020-03-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0007_book_order_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_order',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
