# Generated by Django 3.0.4 on 2020-03-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0008_book_order_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
