# Generated by Django 3.0.4 on 2020-03-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0009_book_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
        migrations.CreateModel(
            name='Borrowed_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin2.Book')),
            ],
        ),
    ]
