# Generated by Django 3.0.4 on 2020-03-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_member_accepted'),
        ('admin2', '0010_auto_20200309_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member'),
        ),
    ]
