# Generated by Django 3.0.4 on 2020-03-09 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0011_borrowed_book_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
