# Generated by Django 3.0.4 on 2020-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0013_auto_20200313_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_book',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
