# Generated by Django 3.0.4 on 2020-03-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0015_book_order_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_order',
            name='return_date',
        ),
        migrations.AddField(
            model_name='book_order',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
