# Generated by Django 3.0.4 on 2020-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
