# Generated by Django 3.0.4 on 2020-03-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='accepted',
        ),
    ]
